image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn install && yarn build && pip3 install platformio
    command: PATH=$PATH:$HOME/.local/bin node server/app.js
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
